<?php
	$aff_meta_keys = array(
	    // 'entry_id',
	    // 'order',
	    // 'entry_type',
	    // 'visibility',
	    // 'categories',
	    // 'family_name',
	    // 'honorific_prefix',
	    'first_name',
	    'middle_name',
	    'last_name',
	    // 'honorific_suffix',
	    'title',
	    // 'organization',
	    // 'department',
	    'contact_first_name',
	    'contact_last_name',
	    // 'home_address_line_one',
	    // 'home_address_line_two',
	    // 'home_address_line_three',
	    // 'home_address_line_four',
	    // 'home_address_district',
	    // 'home_address_county',
	    // 'home_address_city',
	    // 'home_address_state',
	    // 'home_address_zipcode',
	    // 'home_address_country',
	    // 'home_address_latitude',
	    // 'home_address_longitude',
	    // 'home_address_visibility',
	    'work_address_line_one',
	    'work_address_line_two',
	    'work_address_line_three',
	    'work_address_line_four',
	    'work_address_district',
	    'work_address_county',
	    'work_address_city',
	    'work_address_state',
	    'work_address_zipcode',
	    'work_address_country',
	    // 'work_address_latitude',
	    // 'work_address_longitude',
	    // 'work_address_visibility',
	    'phone_cell_phone_number',
	    // 'phone_cell_phone_visibility',
	    // 'phone_home_phone_number',
	    // 'phone_home_phone_visibility',
	    'phone_work_fax_number',
	    // 'phone_work_fax_visibility',
	    'phone_work_phone_number',
	    // 'phone_work_phone_visibility',
	    'email_personal_email_address',
	    // 'email_personal_email_visibility',
	    'email_work_email_address',
	    // 'email_work_email_visibility',
	    'social_network_facebook_url',
	    // 'social_network_facebook_visibility',
	    'social_network_linkedin_url',
	    // 'social_network_linkedin_visibility',
	    'social_network_twitter_url',
	    // 'social_network_twitter_visibility',
	    // 'im_uid',
	    // 'im_visibility',
	    'link_website_url',
	    // 'link_website_title',
	    // 'link_website_visibility',
	    // 'dates_date',
	    // 'dates_visibility',
	    // 'biography',
	    'notes',
	    // 'photo_url',
	    'logo_url',
	);